# BOIA Analysis

In [1]:
import pandas as pd
import xarray as xr

In [12]:
## config
BOIAS = {
    'PE-1': {
        'arquivo':  'SIMCOSTA_PE-1_MET_2024-09-20_2025-08-19.csv',
        'drive_id': '16xCqu_7aC4RfwFNXdkyk2DyjxwwQ8SHu',
        'nome':     'PE-1 (Pernambuco)',
        'lat':      -8.77430555,
        'lon':      -35.08358333,
        'cor':      '#1f77b4',
    },
    'Pecem': {
        'arquivo':  'SIMCOSTA_PNBoia_Pecem_MET_2024-09-28_2026-03-01.csv',
        'drive_id': '14_rkb3agXY36ftAK1ZJ-feCnOp2dq640',
        'nome':     'PNBoia Pecem (Ceara)',
        'lat':      -3.54288,
        'lon':      -38.78345,
        'cor':      '#ff7f0e',
    },
}

MESES = ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun',
         'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez']

print('Configurations OK:')
for nome, cfg in BOIAS.items():
    print(f'  {nome}: {cfg["arquivo"]}  |  lat={cfg["lat"]}  lon={cfg["lon"]}')

Configurations OK:
  PE-1: SIMCOSTA_PE-1_MET_2024-09-20_2025-08-19.csv  |  lat=-8.77430555  lon=-35.08358333
  Pecem: SIMCOSTA_PNBoia_Pecem_MET_2024-09-28_2026-03-01.csv  |  lat=-3.54288  lon=-38.78345

In [4]:
df1 = pd.read_table('SIMCOSTA_PE-1_MET_2024-09-20_2025-08-19.csv')
df1

                  /SiMCosta PE-1
0        /latitude = -8.77430555
1      /longitude = -35.08358333
2                  /depth = 15.8
3                      /L1 data
4                /missing = NULL
...                          ...
2672     2025,8,19,3,0,1,6.4,131
2673     2025,8,19,6,0,1,4.4,142
2674     2025,8,19,9,0,1,5.2,142
2675      2025,8,19,12,0,1,0,108
2676  2025,8,19,15,0,1,NULL,NULL

[2677 rows x 1 columns]

In [11]:
df1 = pd.read_csv('SIMCOSTA_PE-1_MET_2024-09-20_2025-08-19.csv', sep='\t')
df1

                  /SiMCosta PE-1
0        /latitude = -8.77430555
1      /longitude = -35.08358333
2                  /depth = 15.8
3                      /L1 data
4                /missing = NULL
...                          ...
2672     2025,8,19,3,0,1,6.4,131
2673     2025,8,19,6,0,1,4.4,142
2674     2025,8,19,9,0,1,5.2,142
2675      2025,8,19,12,0,1,0,108
2676  2025,8,19,15,0,1,NULL,NULL

[2677 rows x 1 columns]